### ISSUE TITLE
В классе Player, метод - sumGenre, не суммирует проигранное время 

### ISSUE THREAD

**Issue by yanabialkova** [yanabialkova/TeamProject#1]
<h2>Описание</h2>
В классе Player, метод - sumGenre, не суммирует проигранное время 

<h2>Локация дефекты</h2>

https://github.com/yanabialkova/TeamProject/blob/bc1482dac9e30bda59975c4d625f31340cd9eb9f/src/main/java/ru/netology/Player.java#L45-L55

<h2> Шаги воспроизведения</h2> 

1. Открыть код программы [https://github.com/yanabialkova/TeamProject/blob/master/src/main/java/ru/netology/Player.java](url) в IDEA.
2. Открыть код программы [https://github.com/yanabialkova/TeamProject/blob/master/src/test/java/ru/netology/PlayerTest.java](url) в IDEA.
3. Создать пустой объект нашей **GameStore.**
4. Создать объект игры при помощи метода **publishGame.**
5. Создать пустой объект нашей **Player.**
6. Создать объект игры при помощи метода **installGame.**
7. Создать объект проигранных часов при помощи метода **play.**
8. Выставить значение переменной **expected** - 3.
9. Выставить значение переменной **actual** - с помощью метода **sumGenre**.
10. С помощью **assertEquals** проверить **expected** и **actual**.

**Ожидаемый результат** - 3
**Фактический результат** - 0.

<h2> Скриншоты</h2> 

<img width="742" alt="Снимок экрана 2022-07-09 в 12 40 37" src="https://user-images.githubusercontent.com/95763360/178102435-0b55d1d4-a8d8-4221-a9c7-d021661feaed.png">
<img width="754" alt="Снимок экрана 2022-07-09 в 12 41 51" src="https://user-images.githubusercontent.com/95763360/178102440-f75923fc-f683-46bd-8f93-1d472046fc99.png">

<h2> Окружение</h2> 

Операционная система: MacBook Pro (Retina, 13-inch, Early 2015)
IDE: IntelliJ IDEA 2021.2.3 (Community Edition)
Java: OpenJDK 11

**Comment by ElinaHaf** [comment]
Closed
