### ISSUE TITLE
В классе Player, метод - play, если игра не была установлена, НЕ выкидывает RuntimeException 

### ISSUE THREAD

**Issue by yanabialkova** [yanabialkova/TeamProject#10]
<h2>Описание </h2>
В классе Player, метод - play, если игра не была установлена, НЕ выкидывает RuntimeException 

<h2>Локация дефекта</h2>

https://github.com/yanabialkova/TeamProject/blob/bc1482dac9e30bda59975c4d625f31340cd9eb9f/src/main/java/ru/netology/Player.java#L32

<h2>Шаги воспроизведения </h2>

1. Открыть код программы [https://github.com/yanabialkova/TeamProject/blob/master/src/main/java/ru/netology/Player.java](https://github.com/yanabialkova/TeamProject/issues/url) в IDEA.
2. Открыть код программы [https://github.com/yanabialkova/TeamProject/blob/master/src/test/java/ru/netology/PlayerTest.java](https://github.com/yanabialkova/TeamProject/issues/url) в IDEA.
3. Написать тест, где нужно установить значение, что игра не была установлена.
4. Запустить программу.
5. Посмотреть на вывод в консоли.

**Ожидаемый результат** - Вывод сообщения об успешном прохождении теста.
**Фактический результат** - Вывод сообщения об ошибке.

<h2>Скриншоты</h2>
<img width="906" alt="Снимок экрана 2022-07-10 в 14 42 58" src="https://user-images.githubusercontent.com/95763360/178145538-a4f0cc00-783c-4e36-a96e-6bf5d8b79e96.png">

<h2>Окружение</h2>
Операционная система: 

- MacBook Pro (Retina, 13-inch, Early 2015)
- IDE: IntelliJ IDEA 2021.2.3 (Community Edition)
- Java: OpenJDK 11

**Comment by ElinaHaf** [comment]
Closed
