### ISSUE TITLE
В классе Player, не реализован метод - mostPlayerByGenre

### ISSUE THREAD

**Issue by yanabialkova** [yanabialkova/TeamProject#2]
<h2>Описание</h2>
В классе Player, не реализован метод - mostPlayerByGenre

<h2>Локация дефекты</h2>

https://github.com/yanabialkova/TeamProject/blob/bc1482dac9e30bda59975c4d625f31340cd9eb9f/src/main/java/ru/netology/Player.java#L59-L61

<h2>Шаги воспроизведения</h2>

1. Открыть код программы [https://github.com/yanabialkova/TeamProject/blob/master/src/main/java/ru/netology/Player.java](https://github.com/yanabialkova/TeamProject/issues/url) в IDEA.

**Ожидаемый результат** - метод реализован, есть возможность посчитать в какую игру играли больше всего.
**Фактический результат** - метод не реализован.

<h2>Скриншоты</h2>

<img width="749" alt="Снимок экрана 2022-07-09 в 14 10 54" src="https://user-images.githubusercontent.com/95763360/178105187-17a450ba-52db-4360-9450-2627cc687ae8.png">

<h2>Окружение</h2>

- Операционная система: MacBook Pro (Retina, 13-inch, Early 2015)
- IDE: IntelliJ IDEA 2021.2.3 (Community Edition)
- Java: OpenJDK 11

**Comment by ElinaHaf** [comment]
Closed
