### ISSUE TITLE
В классе GameStore переменная i цикла For метода containsGame не должна быть равна 1

### ISSUE THREAD

**Issue by ElinaHaf** [yanabialkova/TeamProject#3]

**Comment by ElinaHaf** [comment]
# Описание
В классе GameStore переменная i цикла For метода containsGame не должна быть равна 1

# Локация дефекта
https://github.com/yanabialkova/TeamProject/blob/bc1482dac9e30bda59975c4d625f31340cd9eb9f/src/main/java/ru/netology/GameStore.java#L33

# Шаги воспроизведения
1. Открыть [код программы] (https://github.com/yanabialkova/TeamProject/blob/master/src/main/java/ru/netology/GameStore.java#L33)
2. Выставить значение переменной i = 1
3. Открыть [код программы](https://github.com/yanabialkova/TeamProject/blob/master/src/test/java/ru/netology/GameStoreTest.java)
4. Запустить программу
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения об удачном прохождении теста
*Фактический результат:* Вывод сообщения о неудачном прохождении теста

# Скриншот
![Issue 3](https://user-images.githubusercontent.com/103569727/178108279-f0a28b69-9fb7-4b70-bd90-8a33a4af4ae5.jpg)

# Окружение
* **Операционная система** Windows 7 Профессиональная
* **IDE:** IntelliJ IDEA 2022.1.1 (Community Edition)
* **Java:** 11.0.14.1+1-b2043.45 amd64

**Comment by ElinaHaf** [comment]
# Описание 
Переменная i цикла For в классе GameStore метода containsGame не должна быть равна 1.

# Локация дефекта
https://github.com/yanabialkova/TeamProject/blob/bc1482dac9e30bda59975c4d625f31340cd9eb9f/src/main/java/ru/netology/GameStore.java#L33

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/yanabialkova/TeamProject/blob/master/src/main/java/ru/netology/GameStore.java#L33)
2. Выставить значение переменной i = 1
3. Открыть [код программы](https://github.com/yanabialkova/TeamProject/blob/master/src/test/java/ru/netology/GameStoreTest.java)
4. Запустить программу
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения об успешном прохождении теста
*Фактический результат:* Вывод сообщения о неудачном прохождении теста

# Скриншот
![Issue 3](https://user-images.githubusercontent.com/103569727/178107461-244f09d9-2ca5-407a-9e3d-e09bae29d462.jpg)

# Окружение
* **Операционная система** Windows 7 Профессиональная
* **IDE:** IntelliJ IDEA 2022.1.1 (Community Edition)
* **Java:** 11.0.14.1+1-b2043.45 amd64

**Comment by yanabialkova** [comment]
close
