### ISSUE TITLE
В классе GameStore длина списка games в условном операторе if не может иметь отрицательное значение

### ISSUE THREAD

**Issue by ElinaHaf** [yanabialkova/TeamProject#4]
# Описание
В классе GameStore длина списка games в условном операторе if не может иметь отрицательное значение.

# Локация дефекта
https://github.com/yanabialkova/TeamProject/blob/bc1482dac9e30bda59975c4d625f31340cd9eb9f/src/main/java/ru/netology/GameStore.java#L34

# Шаги воспроизведения
1. Открыть [код программы] (https://github.com/yanabialkova/TeamProject/blob/master/src/main/java/ru/netology/GameStore.java#L33)
2. Выставить значение длины списка (i - 1)
3. Открыть [код программы](https://github.com/yanabialkova/TeamProject/blob/master/src/test/java/ru/netology/GameStoreTest.java)
4. Запустить программу
5. Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения об удачном прохождении теста
*Фактический результат:* Вывод сообщения о неудачном прохождении теста

# Скриншот
![Issue 4](https://user-images.githubusercontent.com/103569727/178108952-325ec1d4-8a6d-4e4d-ac90-6a3fb069df9f.jpg)
# Окружение
* **Операционная система**  Windows 7 Профессиональная
* **IDE:** IntelliJ IDEA 2022.1.1 (Community Edition)
* **Java:**  11.0.14.1+1-b2043.45 amd64

**Comment by yanabialkova** [comment]
close
