### ISSUE TITLE
В классе Player, метод - play, не добавляет проигранное количество часов к суммарному количество часов

### ISSUE THREAD

**Issue by yanabialkova** [yanabialkova/TeamProject#6]
<h2>Описание 2</h2>
В классе Player, метод - play, не добавляет проигранное количество часов к суммарному количество часов

<h2>Локация дефекты 2</h2>

https://github.com/yanabialkova/TeamProject/blob/bc1482dac9e30bda59975c4d625f31340cd9eb9f/src/main/java/ru/netology/Player.java#L36

<h2>Шаги воспроизведения 2</h2>

1. Открыть код программы [https://github.com/yanabialkova/TeamProject/blob/master/src/main/java/ru/netology/Player.java](https://github.com/yanabialkova/TeamProject/issues/url) в IDEA.
2. Открыть код программы [https://github.com/yanabialkova/TeamProject/blob/master/src/test/java/ru/netology/PlayerTest.java](https://github.com/yanabialkova/TeamProject/issues/url) в IDEA.
3. Создать пустой объект нашей **Player**.
4. Создать пустой объект нашей **GameStore.**
5. Создать объект игры при помощи метода **publishGame.**
6. Создать объект сумированных часов при помощи метода **sumGenre.**
7. Выставить значение переменной **expected** - 4.
8. Выставить значение переменной **actual** - с помощью метода **play**.
9. Запустить программу.
10. Посмотреть на вывод в консоли.

**Ожидаемый результат** - 4.
**Фактический результат** - 0.

<h2>Скриншоты 2</h2>

<img width="711" alt="Снимок экрана 2022-07-09 в 16 40 29" src="https://user-images.githubusercontent.com/95763360/178110535-11676198-c3cc-4650-ba6e-9f76cab05522.png">

<h2>Окружение 2</h2>

Операционная система: MacBook Pro (Retina, 13-inch, Early 2015)
IDE: IntelliJ IDEA 2021.2.3 (Community Edition)
Java: OpenJDK 11

**Comment by ElinaHaf** [comment]
Closed
