### ISSUE TITLE
В классе GameStore методa addPlayTime в условном операторе if значение не суммируется с прошлым значением hours игрока.

### ISSUE THREAD

**Issue by ElinaHaf** [yanabialkova/TeamProject#7]
# Описание
В методе addPlayTime класса GameStore в условном операторе if значение не суммируется с прошлым значением hours игрока.

# Локация дефекта
https://github.com/yanabialkova/TeamProject/blob/bc1482dac9e30bda59975c4d625f31340cd9eb9f/src/main/java/ru/netology/GameStore.java#L48

# Шаги воcпроизведения
1. Открыть [код программы](https://github.com/yanabialkova/TeamProject/blob/master/src/main/java/ru/netology/GameStore.java)
2. Открыть [код программы](https://github.com/yanabialkova/TeamProject/blob/master/src/test/java/ru/netology/GameStoreTest.java)
3. Написать тест на поиск игрока с максимальным количеством отыгранного времени.
4. Запустить программу
5. Посмотреть на выход в консоли

*Ожидаемый результат:* Вывод сообщения об успешном прохождении теста 
*Ожидаемый результат:* Вывод сообщения об ошибке

# Скриншот
![Issue 6](https://user-images.githubusercontent.com/103569727/178119042-fefaa9b6-4963-4ae2-8140-0e637056d531.jpg)

# Окружение
* **Операционная система** Windows 7 Профессиональная
* **IDE:** IntelliJ IDEA 2022.1.1 (Community Edition)
* **Java:** 11.0.14.1+1-b2043.45 amd64

**Comment by yanabialkova** [comment]
close
