### ISSUE TITLE
В классе GameStore в методе поиска игрока с максимальным проигранным временем переменная mostTime не должна быть равна 1

### ISSUE THREAD

**Issue by ElinaHaf** [yanabialkova/TeamProject#8]
# Описание
В классе GameStore метод поиска игрока с максимальным проигранным временем (getMostPlayer) переменная mostTime не должна быть равна 1

# Локация дефекта
https://github.com/yanabialkova/TeamProject/blob/bc1482dac9e30bda59975c4d625f31340cd9eb9f/src/main/java/ru/netology/GameStore.java#L59

# Шаги вопроизведения
1. Открыть [код программы](https://github.com/yanabialkova/TeamProject/blob/master/src/main/java/ru/netology/GameStore.java)
2. Выставить значение переменной int mostTime = 1
3. Открыть [код программы](https://github.com/yanabialkova/TeamProject/blob/master/src/test/java/ru/netology/GameStoreTest.java)
4. Написать тест на поиск игрока с максимальным количеством отыгранных часов, где единственный игрок отыграл в игры данного каталога 1 час
5. Запустить программу
6. Смотреть на вывод в консоли

*Ожидаемый результат* Вывод сообщения об успешном прохождении теста
*Фактический результат* Вывод сообщения об ошибке

# Скриншот
![Issue 7](https://user-images.githubusercontent.com/103569727/178119701-08e2cdf9-d42a-4b3c-9acb-9d96feb1455e.jpg)

# Окружение
* **Операционная система** Windows 7 Профессиональная
* **IDE:** IntelliJ IDEA 2022.1.1 (Community Edition)
* **Java:** 11.0.14.1+1-b2043.45 amd64

**Comment by yanabialkova** [comment]
close
