### ISSUE TITLE
В классе GameStore метод getSumPlayedTime не возвращает сумму времени всех игроков

### ISSUE THREAD

**Issue by ElinaHaf** [yanabialkova/TeamProject#9]
# Описание
В классе GameStore метод getSumPlayedTime не возвращает сумму времени всех игроков

#Локация дефекта
https://github.com/yanabialkova/TeamProject/blob/bc1482dac9e30bda59975c4d625f31340cd9eb9f/src/main/java/ru/netology/GameStore.java#L75
https://github.com/yanabialkova/TeamProject/blob/bc1482dac9e30bda59975c4d625f31340cd9eb9f/src/main/java/ru/netology/GameStore.java#L76
https://github.com/yanabialkova/TeamProject/blob/bc1482dac9e30bda59975c4d625f31340cd9eb9f/src/main/java/ru/netology/GameStore.java#L77
https://github.com/yanabialkova/TeamProject/blob/bc1482dac9e30bda59975c4d625f31340cd9eb9f/src/main/java/ru/netology/GameStore.java#L78

# Шаги вопросизведения
1. Открыть [код программы](https://github.com/yanabialkova/TeamProject/blob/master/src/main/java/ru/netology/GameStore.java)  в Idea 
2. Выставить значение return = 0;
3. Открыть [код программы](https://github.com/yanabialkova/TeamProject/blob/master/src/test/java/ru/netology/GameStoreTest.java) в Idea
4. Написать тест на расчет суммы проигранного времени всех игроков этого каталога (shouldGetSumPlayedTime), добавить методом addPlayTime игроков с отыгранным временем
5. Запустить программу
6. Смотреть на вывод сообщения в консоли

*Ожидаемый результат* Вывод сообщения об успешном прохождении теста
*Фактический результат* Вывод сообщения об ошибке Actual = 0

# Скриншот
![Issue 8](https://user-images.githubusercontent.com/103569727/178139135-daa5edce-fec6-4d18-8a62-c5fe71a008f0.jpg)

# Окружение
* **Операционная система** Windows 7 Профессиональная
* **IDE:** IntelliJ IDEA 2022.1.1 (Community Edition)
* **Java:** 11.0.14.1+1-b2043.45 amd64

**Comment by yanabialkova** [comment]
close
